### ISSUE TITLE
Import SVG from Affinity Designer

### ISSUE THREAD

**Issue by RGPaul** [k-o-d-e-n/charlottie-page#2]
Hi,

thanks for the App.

I can't import SVGs into the App that I exported using Affinity Designer. I tried different options, but nothing worked yet.

**Comment by k-o-d-e-n** [comment]
Hi. Thank you for report.
Can you send me your svg?

**Comment by RGPaul** [comment]
Hey, sure.
![Test](https://user-images.githubusercontent.com/406982/198965271-18c0f8eb-5fb8-4aca-bfe8-f68a8aecd4b6.svg)

**Comment by k-o-d-e-n** [comment]
Just open as regular file. Currently Charlottie requires some filling for SVG objects. You can add color in your SVG editor, or in Charlottie app like in video.

https://user-images.githubusercontent.com/18463658/199001469-907973ce-0989-4662-a640-3a172c7e742c.MOV

**Comment by RGPaul** [comment]
Thanks
