### ISSUE TITLE
Adding SVG data to existing animation

### ISSUE THREAD

**Issue by RGPaul** [k-o-d-e-n/charlottie-page#3]
Is it possible to add vector data (via svg) to an existing animation?
I can import svg but that creates an image layer that cannot animate the vector data.

**Comment by k-o-d-e-n** [comment]
It was possible, but in current version I cannot do it. It shows error always. I will fix it, when I have time enough.
Thank you!

**Comment by k-o-d-e-n** [comment]
I fixed it, try again please in [TestFlight](https://testflight.apple.com/join/AwyGVVVl)

**Comment by RGPaul** [comment]
Works - Thanks alot!
