### ISSUE TITLE
Possible to animate a movement along a path?

### ISSUE THREAD

**Issue by RGPaul** [k-o-d-e-n/charlottie-page#4]
Is it possible to animate a movement along a path (eg. a curve)?

**Comment by k-o-d-e-n** [comment]
It isn't possible in sense of Adobe After Effects (with element rotation), but you can edit movement path and rotate element manually.

https://user-images.githubusercontent.com/18463658/201415019-0737ad94-e2d7-4fac-bbdb-9fe0cec15010.mp4

**Comment by RGPaul** [comment]
That is exactly what I was looking for. Thank You!

**Comment by k-o-d-e-n** [comment]
To change mode of point use double tap.
